version: '3.6'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - database

  database:
    image: postgres:11.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    container_name: postgres
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=api_development
       - POSTGRES_HOST_AUTH_METHOD=trust