name: Docker Image CI Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file client/Dockerfile --tag client:$(date +%s)
    
    - name: Run Tests
      run: docker run client yarn run test:unit
