name: Docker Image CI

on:
  push:
    paths:
      - "api/*"
    branches: [ master ]
  pull_request:
    paths:
      - "api/*"
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    
    - name: Create and Migrate DB
      run: docker-compose run api rails db:create db:migrate
    
    - name: Run Tests
      run: docker-compose run api rails test
