name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    
    - name: Create and Migrate DB
      run: docker-compose run api rails db:create db:migrate
    
    - name: Run Tests
      run: docker-compose run api rails test

    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_ID}}
      with:
        coverageCommand: docker-compose run api rails cov
        debug: true