name: Docker Image CI Client

on:
  push:
    paths:
      - "client/*"
    branches: [ master ]
  pull_request:
    paths:
      - "client/*"
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t client client/. 
    - name: Run Tests
      run: docker run client yarn run test:unit
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
